vich_uploader:
    db_driver: orm

    mappings:
        media:
            uri_prefix: /api/media
            upload_destination: '%kernel.project_dir%/media'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            inject_on_load: true