#index:
#    path: /
#    controller: App\Controller\DefaultController::index

authentication_token:
    path: /api/authentication_token
    methods: ['POST']

gesdinet_jwt_refresh_token:
  path:       /api/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh

swagger_ui:
    path: /docs
    controller: api_platform.swagger.action.ui